services:
  db:
    container_name: stockgpt-db
    image: postgres:15.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
    shm_size: 512mb

  qdrant:
    container_name: stockgpt-qdrant
    image: qdrant/qdrant:v1.2.0
    ports:
      - "6333:6333"
    environment:
      QDRANT_HOST: ${QDRANT_HOST}
      QDRANT_PORT: ${QDRANT_PORT}
      QDRANT_COLLECTION_ORGS: ${QDRANT_COLLECTION_ORGS}
      QDRANT_COLLECTION_SERVICES: ${QDRANT_COLLECTION_SERVICES}
    volumes:
      - qdrant-data:/qdrant/storage
    restart: unless-stopped

volumes:
  db-data:
    name: stockgpt-db-data
  qdrant-data:
    name: stockgpt-qdrant-data
